# ????? ????? ?????????????? ?? (? ?.?.)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres
    hikari:
      schema: tasks_schema #??? ????? ??. ?????? ???? ??????? ?????????? Task Repository, ??????? ????? ???????? ? ?? - com/example/simple_web/repository/DataBaseTaskRepository
  application:
    name: simple-web
  profiles:
    active: v3

server:
  port: 8080

logging:
  level:
    com.example.simple_web: DEBUG



# - v1 - ???????????? ??? "???????????" ??????????
# - v2 - ???????????? ??? ??????????????? "???-?-?????" ??????????
# - v3 - ???????????? ??? jdbc ??????????
