spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks?currentSchema=tasks_schema
    username: postgres
    password: postgres
  application:
    name: simple-web
  profiles:
    active: v3

server:
  port: 8080

logging:
  level:
    com.example.simple_web: DEBUG